### ISSUE TITLE
'primordials is not defined' on npm install

### ISSUE THREAD

**Issue by socalledsound** [BrendonCon/vector2#7]
Hi, is this still maintained?
I'm getting a build error: 

> vector2@0.0.1 postinstall
> gulp build && gulp dist

[10:02:12] Failed to load external module @babel/register
[10:02:12] Requiring external module babel-register
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/Users/ck/Desktop/vector2/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/ck/Desktop/vector2/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/ck/Desktop/vector2/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/ck/Desktop/vector2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR! code 1
npm ERR! path /Users/ck/Desktop/vector2
npm ERR! command failed
npm ERR! command sh -c gulp build && gulp dist

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ck/.npm/_logs/2022-10-10T17_02_12_486Z-debug.log

**Comment by BrendonCon** [comment]
Hey there, haven't visited this project in a while but wouldn't mind sorting this out, I suspect something to do with old node modules in relation to modern systems, will take a look and feedback

**Comment by BrendonCon** [comment]
Hey there, I have upgrade gulp to 4 and this error no longer persists. However the build system needs to be changed to suit gulp 4. Just going to fix that and add some more methods to the class. Thanks so much and sorry for the delay, I work full time and am busy with a degree, so apologies for the delay!
